export default {
  "a2z-195": { approaches: [
    { id: "pick-digits", title: "Choose increasing digits to hit count/sum", level: "Optimal", time: "O(9!/(k!))", space: "O(k)",
      explanation: "Recurse over digits 1..9 keeping them strictly increasing, stopping at k digits; keep those summing to n.",
      code: {
        java: "class Solution {\n    java.util.List<java.util.List<Integer>> combinationSum3(int k, int n) {\n        java.util.List<java.util.List<Integer>> res = new java.util.ArrayList<>();\n        bt(res, new java.util.ArrayList<>(), k, n, 1);\n        return res;\n    }\n    void bt(java.util.List<java.util.List<Integer>> res, java.util.List<Integer> cur, int k, int left, int start) {\n        if (cur.size() == k) {\n            if (left == 0) res.add(new java.util.ArrayList<>(cur));\n            return;\n        }\n        for (int d = start; d <= 9; d++) {\n            cur.add(d);\n            bt(res, cur, k, left - d, d + 1);\n            cur.remove(cur.size() - 1);\n        }\n    }\n}",
        csharp: "public class Solution {\n    public IList<IList<int>> CombinationSum3(int k, int n) {\n        var res = new List<IList<int>>();\n        Bt(res, new List<int>(), k, n, 1);\n        return res;\n    }\n    void Bt(List<IList<int>> res, List<int> cur, int k, int left, int start) {\n        if (cur.Count == k) {\n            if (left == 0) res.Add(new List<int>(cur));\n            return;\n        }\n        for (int d = start; d <= 9; d++) {\n            cur.Add(d);\n            Bt(res, cur, k, left - d, d + 1);\n            cur.RemoveAt(cur.Count - 1);\n        }\n    }\n}"
      } }
  ] },
  "a2z-196": { approaches: [
    { id: "index-map-backtrack", title: "Recurse over digit-to-letter maps", level: "Optimal", time: "O(4^n n)", space: "O(n)",
      explanation: "Map each phone digit to its letters and build every combination one position at a time.",
      code: {
        java: "class Solution {\n    static final String[] MAP = { \"\", \"\", \"abc\", \"def\", \"ghi\", \"jkl\", \"mno\", \"pqrs\", \"tuv\", \"wxyz\" };\n    java.util.List<String> letterCombinations(String digits) {\n        java.util.List<String> res = new java.util.ArrayList<>();\n        if (digits.isEmpty()) return res;\n        bt(res, new StringBuilder(), digits, 0);\n        return res;\n    }\n    void bt(java.util.List<String> res, StringBuilder sb, String d, int i) {\n        if (i == d.length()) {\n            res.add(sb.toString());\n            return;\n        }\n        for (char c : MAP[d.charAt(i) - '0'].toCharArray()) {\n            sb.append(c);\n            bt(res, sb, d, i + 1);\n            sb.deleteCharAt(sb.length() - 1);\n        }\n    }\n}",
        csharp: "public class Solution {\n    static readonly string[] Map = { \"\", \"\", \"abc\", \"def\", \"ghi\", \"jkl\", \"mno\", \"pqrs\", \"tuv\", \"wxyz\" };\n    public IList<string> LetterCombinations(string digits) {\n        var res = new List<string>();\n        if (digits.Length == 0) return res;\n        Bt(res, new StringBuilder(), digits, 0);\n        return res;\n    }\n    void Bt(List<string> res, StringBuilder sb, string d, int i) {\n        if (i == d.Length) {\n            res.Add(sb.ToString());\n            return;\n        }\n        foreach (char c in Map[d[i] - '0']) {\n            sb.Append(c);\n            Bt(res, sb, d, i + 1);\n            sb.Length--;\n        }\n    }\n}"
      } }
  ] },
  "a2z-197": { approaches: [
    { id: "cut-if-palindrome", title: "Cut only at palindromic prefixes", level: "Optimal", time: "O(n 2^n)", space: "O(n^2)",
      explanation: "From each start, extend the current part; recurse further only when that substring is a palindrome.",
      code: {
        java: "class Solution {\n    java.util.List<java.util.List<String>> partition(String s) {\n        java.util.List<java.util.List<String>> res = new java.util.ArrayList<>();\n        bt(res, new java.util.ArrayList<>(), s, 0);\n        return res;\n    }\n    void bt(java.util.List<java.util.List<String>> res, java.util.List<String> cur, String s, int start) {\n        if (start == s.length()) {\n            res.add(new java.util.ArrayList<>(cur));\n            return;\n        }\n        for (int end = start; end < s.length(); end++) {\n            if (isPal(s, start, end)) {\n                cur.add(s.substring(start, end + 1));\n                bt(res, cur, s, end + 1);\n                cur.remove(cur.size() - 1);\n            }\n        }\n    }\n    boolean isPal(String s, int l, int r) {\n        while (l < r) if (s.charAt(l++) != s.charAt(r--)) return false;\n        return true;\n    }\n}",
        csharp: "public class Solution {\n    public IList<IList<string>> Partition(string s) {\n        var res = new List<IList<string>>();\n        Bt(res, new List<string>(), s, 0);\n        return res;\n    }\n    void Bt(List<IList<string>> res, List<string> cur, string s, int start) {\n        if (start == s.Length) {\n            res.Add(new List<string>(cur));\n            return;\n        }\n        for (int end = start; end < s.Length; end++) {\n            if (IsPal(s, start, end)) {\n                cur.Add(s.Substring(start, end - start + 1));\n                Bt(res, cur, s, end + 1);\n                cur.RemoveAt(cur.Count - 1);\n            }\n        }\n    }\n    bool IsPal(string s, int l, int r) {\n        while (l < r) if (s[l++] != s[r--]) return false;\n        return true;\n    }\n}"
      } }
  ] },
  "a2z-198": { approaches: [
    { id: "grid-dfs", title: "DFS with visited marking", level: "Optimal", time: "O(mn 3^L)", space: "O(L)",
      explanation: "From each matching cell, walk the four directions marking the cell as visited and restoring it on backtrack.",
      code: {
        java: "class Solution {\n    boolean exist(char[][] board, String word) {\n        char[] w = word.toCharArray();\n        for (int i = 0; i < board.length; i++)\n            for (int j = 0; j < board[0].length; j++)\n                if (dfs(board, w, i, j, 0)) return true;\n        return false;\n    }\n    boolean dfs(char[][] b, char[] w, int i, int j, int k) {\n        if (k == w.length) return true;\n        if (i < 0 || j < 0 || i >= b.length || j >= b[0].length || b[i][j] != w[k]) return false;\n        char save = b[i][j];\n        b[i][j] = '#';\n        boolean ok = dfs(b, w, i + 1, j, k + 1) || dfs(b, w, i - 1, j, k + 1)\n            || dfs(b, w, i, j + 1, k + 1) || dfs(b, w, i, j - 1, k + 1);\n        b[i][j] = save;\n        return ok;\n    }\n}",
        csharp: "public class Solution {\n    public bool Exist(char[][] board, string word) {\n        char[] w = word.ToCharArray();\n        for (int i = 0; i < board.Length; i++)\n            for (int j = 0; j < board[0].Length; j++)\n                if (Dfs(board, w, i, j, 0)) return true;\n        return false;\n    }\n    bool Dfs(char[][] b, char[] w, int i, int j, int k) {\n        if (k == w.Length) return true;\n        if (i < 0 || j < 0 || i >= b.Length || j >= b[0].Length || b[i][j] != w[k]) return false;\n        char save = b[i][j];\n        b[i][j] = '#';\n        bool ok = Dfs(b, w, i + 1, j, k + 1) || Dfs(b, w, i - 1, j, k + 1)\n            || Dfs(b, w, i, j + 1, k + 1) || Dfs(b, w, i, j - 1, k + 1);\n        b[i][j] = save;\n        return ok;\n    }\n}"
      } }
  ] },
  "a2z-199": { approaches: [
    { id: "column-backtrack", title: "Place one queen per column", level: "Optimal", time: "O(n!)", space: "O(n)",
      explanation: "Fill column by column, checking the row and both diagonals; record the board when all n queens are placed.",
      code: {
        java: "class Solution {\n    java.util.List<java.util.List<String>> solveNQueens(int n) {\n        java.util.List<java.util.List<String>> res = new java.util.ArrayList<>();\n        char[][] board = new char[n][n];\n        for (char[] r : board) java.util.Arrays.fill(r, '.');\n        bt(res, board, 0, n);\n        return res;\n    }\n    void bt(java.util.List<java.util.List<String>> res, char[][] b, int col, int n) {\n        if (col == n) {\n            java.util.List<String> snap = new java.util.ArrayList<>();\n            for (int i = 0; i < n; i++) snap.add(new String(b[i]));\n            res.add(snap);\n            return;\n        }\n        for (int row = 0; row < n; row++) {\n            if (safe(b, row, col, n)) {\n                b[row][col] = 'Q';\n                bt(res, b, col + 1, n);\n                b[row][col] = '.';\n            }\n        }\n    }\n    boolean safe(char[][] b, int row, int col, int n) {\n        for (int i = 0; i < col; i++) if (b[row][i] == 'Q') return false;\n        for (int i = row, j = col; i >= 0 && j >= 0; i--, j--) if (b[i][j] == 'Q') return false;\n        for (int i = row, j = col; i < n && j >= 0; i++, j--) if (b[i][j] == 'Q') return false;\n        return true;\n    }\n}",
        csharp: "public class Solution {\n    public IList<IList<string>> SolveNQueens(int n) {\n        var res = new List<IList<string>>();\n        char[][] board = new char[n][];\n        for (int i = 0; i < n; i++) { board[i] = new char[n]; Array.Fill(board[i], '.'); }\n        Bt(res, board, 0, n);\n        return res;\n    }\n    void Bt(List<IList<string>> res, char[][] b, int col, int n) {\n        if (col == n) {\n            var snap = new List<string>();\n            for (int i = 0; i < n; i++) snap.Add(new string(b[i]));\n            res.Add(snap);\n            return;\n        }\n        for (int row = 0; row < n; row++) {\n            if (Safe(b, row, col, n)) {\n                b[row][col] = 'Q';\n                Bt(res, b, col + 1, n);\n                b[row][col] = '.';\n            }\n        }\n    }\n    bool Safe(char[][] b, int row, int col, int n) {\n        for (int i = 0; i < col; i++) if (b[row][i] == 'Q') return false;\n        for (int i = row, j = col; i >= 0 && j >= 0; i--, j--) if (b[i, j] == 'Q') return false;\n        for (int i = row, j = col; i < n && j >= 0; i++, j--) if (b[i, j] == 'Q') return false;\n        return true;\n    }\n}"
      } }
  ] },
  "a2z-200": { approaches: [
    { id: "path-dfs", title: "DFS over open cells", level: "Optimal", time: "O(4^(n^2))", space: "O(n^2)",
      explanation: "Move down/right (classic rat-in-maze ordering) through cells equal to 1, marking the path and unmarking on backtrack.",
      code: {
        java: "class Solution {\n    java.util.List<String> findPath(int[][] m, int n) {\n        java.util.List<String> res = new java.util.ArrayList<>();\n        if (m[0][0] == 0) return res;\n        int[][] path = new int[n][n];\n        dfs(m, n, 0, 0, path, new StringBuilder(), res);\n        return res;\n    }\n    void dfs(int[][] m, int n, int i, int j, int[][] path, StringBuilder sb, java.util.List<String> res) {\n        if (i == n - 1 && j == n - 1) {\n            res.add(sb.toString());\n            return;\n        }\n        if (i < 0 || j < 0 || i >= n || j >= n || m[i][j] == 0 || path[i][j] == 1) return;\n        path[i][j] = 1;\n        int len = sb.length();\n        dfs(m, n, i, j + 1, path, sb.append('R'), res);\n        dfs(m, n, i + 1, j, path, sb.append('D'), res);\n        dfs(m, n, i, j - 1, path, sb.append('L'), res);\n        dfs(m, n, i - 1, j, path, sb.append('U'), res);\n        sb.setLength(len);\n        path[i][j] = 0;\n    }\n}",
        csharp: "public class Solution {\n    public IList<string> FindPath(int[][] m, int n) {\n        var res = new List<string>();\n        if (m[0][0] == 0) return res;\n        int[][] path = new int[n][];\n        for (int i = 0; i < n; i++) path[i] = new int[n];\n        Dfs(m, n, 0, 0, path, new StringBuilder(), res);\n        return res;\n    }\n    void Dfs(int[][] m, int n, int i, int j, int[][] path, StringBuilder sb, List<string> res) {\n        if (i == n - 1 && j == n - 1) {\n            res.Add(sb.ToString());\n            return;\n        }\n        if (i < 0 || j < 0 || i >= n || j >= n || m[i][j] == 0 || path[i][j] == 1) return;\n        path[i][j] = 1;\n        int len = sb.Length;\n        Dfs(m, n, i, j + 1, path, sb.Append('R'), res);\n        Dfs(m, n, i + 1, j, path, sb.Append('D'), res);\n        Dfs(m, n, i, j - 1, path, sb.Append('L'), res);\n        Dfs(m, n, i - 1, j, path, sb.Append('U'), res);\n        sb.Length = len;\n        path[i][j] = 0;\n    }\n}"
      } }
  ] },
  "a2z-201": { approaches: [
    { id: "memo-cut", title: "Top-down memo on the start index", level: "Better", time: "O(n^2 · word)", space: "O(n)",
      explanation: "At each start index try every dictionary word that matches the prefix; memoize which starts can reach the end.",
      code: {
        java: "class Solution {\n    Boolean[] memo;\n    boolean wordBreak(String s, java.util.List<String> dict) {\n        memo = new Boolean[s.length()];\n        return can(s, dict, 0);\n    }\n    boolean can(String s, java.util.List<String> dict, int start) {\n        if (start == s.length()) return true;\n        if (memo[start] != null) return memo[start];\n        for (String w : dict) {\n            int len = w.length();\n            if (start + len <= s.length() && s.startsWith(w, start)\n                && can(s, dict, start + len)) {\n                memo[start] = true;\n                return true;\n            }\n        }\n        memo[start] = false;\n        return false;\n    }\n}",
        csharp: "public class Solution {\n    bool?[] memo;\n    public bool WordBreak(string s, IList<string> dict) {\n        memo = new bool?[s.Length];\n        return Can(s, dict, 0);\n    }\n    bool Can(string s, IList<string> dict, int start) {\n        if (start == s.Length) return true;\n        if (memo[start].HasValue) return memo[start].Value;\n        foreach (string w in dict) {\n            int len = w.Length;\n            if (start + len <= s.Length && s.StartsWith(w, StringComparison.Ordinal)\n                && Can(s, dict, start + len)) {\n                memo[start] = true;\n                return true;\n            }\n        }\n        memo[start] = false;\n        return false;\n    }\n}"
      } }
  ] },
  "a2z-202": { approaches: [
    { id: "vertex-backtrack", title: "Assign colours vertex by vertex", level: "Optimal", time: "O(m^n)", space: "O(n)",
      explanation: "Try each colour for the current vertex, accepting it only when no already-coloured neighbour shares it; recurse to the next vertex.",
      code: {
        java: "class Solution {\n    boolean graphColoring(int[][] graph, int[] colors, int m, int node) {\n        int n = colors.length;\n        if (node == n) return true;\n        for (int c = 1; c <= m; c++) {\n            if (isSafe(graph, colors, node, c)) {\n                colors[node] = c;\n                if (graphColoring(graph, colors, m, node + 1)) return true;\n                colors[node] = 0;\n            }\n        }\n        return false;\n    }\n    boolean isSafe(int[][] graph, int[] colors, int node, int c) {\n        for (int v = 0; v < colors.length; v++)\n            if (v != node && graph[node][v] == 1 && colors[v] == c) return false;\n        return true;\n    }\n}",
        csharp: "public class Solution {\n    public bool GraphColoring(int[][] graph, int[] colors, int m, int node) {\n        int n = colors.Length;\n        if (node == n) return true;\n        for (int c = 1; c <= m; c++) {\n            if (IsSafe(graph, colors, node, c)) {\n                colors[node] = c;\n                if (GraphColoring(graph, colors, m, node + 1)) return true;\n                colors[node] = 0;\n            }\n        }\n        return false;\n    }\n    bool IsSafe(int[][] graph, int[] colors, int node, int c) {\n        for (int v = 0; v < colors.Length; v++)\n            if (v != node && graph[node][v] == 1 && colors[v] == c) return false;\n        return true;\n    }\n}"
      } }
  ] },
  "a2z-203": { approaches: [
    { id: "cell-backtrack", title: "Fill empty cells with valid digits", level: "Optimal", time: "O(9^empty)", space: "O(1)",
      explanation: "Find the next empty cell, try 1..9 that respect row/column/3x3, and recurse; undo when a branch fails.",
      code: {
        java: "class Solution {\n    boolean solveSudoku(char[][] b) {\n        for (int i = 0; i < 9; i++)\n            for (int j = 0; j < 9; j++) {\n                if (b[i][j] == '.') {\n                    for (char c = '1'; c <= '9'; c++) {\n                        if (valid(b, i, j, c)) {\n                            b[i][j] = c;\n                            if (solveSudoku(b)) return true;\n                            b[i][j] = '.';\n                        }\n                    }\n                    return false;\n                }\n            }\n        return true;\n    }\n    boolean valid(char[][] b, int r, int c, char v) {\n        for (int i = 0; i < 9; i++) {\n            if (b[r][i] == v || b[i][c] == v) return false;\n            int br = 3 * (r / 3) + i / 3, bc = 3 * (c / 3) + i % 3;\n            if (b[br][bc] == v) return false;\n        }\n        return true;\n    }\n}",
        csharp: "public class Solution {\n    public bool SolveSudoku(char[][] b) {\n        for (int i = 0; i < 9; i++)\n            for (int j = 0; j < 9; j++) {\n                if (b[i][j] == '.') {\n                    for (char c = '1'; c <= '9'; c++) {\n                        if (Valid(b, i, j, c)) {\n                            b[i][j] = c;\n                            if (SolveSudoku(b)) return true;\n                            b[i][j] = '.';\n                        }\n                    }\n                    return false;\n                }\n            }\n        return true;\n    }\n    bool Valid(char[][] b, int r, int c, char v) {\n        for (int i = 0; i < 9; i++) {\n            if (b[r, i] == v || b[i, c] == v) return false;\n            int br = 3 * (r / 3) + i / 3, bc = 3 * (c / 3) + i % 3;\n            if (b[br, bc] == v) return false;\n        }\n        return true;\n    }\n}"
      } }
  ] },
  "a2z-204": { approaches: [
    { id: "insert-ops-backtrack", title: "Split the string and insert operators", level: "Optimal", time: "O(n 4^n)", space: "O(n)",
      explanation: "At each cut append a digit to the current operand or insert +, -, * (with correct precedence via a previous-term accumulator); keep expressions that evaluate to target.",
      code: {
        java: "class Solution {\n    java.util.List<String> addOperators(String num, int target) {\n        java.util.List<String> res = new java.util.ArrayList<>();\n        bt(res, new StringBuilder(), num, 0, 0, 0, target);\n        return res;\n    }\n    void bt(java.util.List<String> res, StringBuilder path, String num, int idx, long value, long prev, long target) {\n        if (idx == num.length()) {\n            if (value == target) res.add(path.toString());\n            return;\n        }\n        for (int i = idx; i < num.length(); i++) {\n            if (i != idx && num.charAt(idx) == '0') break;\n            long cur = Long.parseLong(num.substring(idx, i + 1));\n            int len = path.length();\n            if (idx == 0) {\n                path.append(cur);\n                bt(res, path, num, i + 1, cur, cur, target);\n                path.setLength(len);\n            } else {\n                path.append('+').append(cur);\n                bt(res, path, num, i + 1, value + cur, cur, target);\n                path.setLength(len);\n                path.append('-').append(cur);\n                bt(res, path, num, i + 1, value - cur, -cur, target);\n                path.setLength(len);\n                path.append('*').append(cur);\n                bt(res, path, num, i + 1, (value - prev) + prev * cur, prev * cur, target);\n                path.setLength(len);\n            }\n        }\n    }\n}",
        csharp: "public class Solution {\n    public IList<string> AddOperators(string num, long target) {\n        var res = new List<string>();\n        Bt(res, new StringBuilder(), num, 0, 0, 0, target);\n        return res;\n    }\n    void Bt(List<string> res, StringBuilder path, string num, int idx, long value, long prev, long target) {\n        if (idx == num.Length) {\n            if (value == target) res.Add(path.ToString());\n            return;\n        }\n        for (int i = idx; i < num.Length; i++) {\n            if (i != idx && num[idx] == '0') break;\n            long cur = long.Parse(num.Substring(idx, i - idx + 1));\n            int len = path.Length;\n            if (idx == 0) {\n                path.Append(cur);\n                Bt(res, path, num, i + 1, cur, cur, target);\n                path.Length = len;\n            } else {\n                path.Append('+').Append(cur);\n                Bt(res, path, num, i + 1, value + cur, cur, target);\n                path.Length = len;\n                path.Append('-').Append(cur);\n                Bt(res, path, num, i + 1, value - cur, -cur, target);\n                path.Length = len;\n                path.Append('*').Append(cur);\n                Bt(res, path, num, i + 1, (value - prev) + prev * cur, prev * cur, target);\n                path.Length = len;\n            }\n        }\n    }\n}"
      } }
  ] }
};
