export default {
  "a2z-238": { approaches: [
    { id: "mono-stack-circular", title: "Monotone stack over 2n", level: "Optimal", time: "O(n)", space: "O(n)",
      explanation: "Traverse the array twice (mod n) using a decreasing stack to find the next greater element in circular order.",
      code: {
        java: "class Solution {\n    int[] nextGreaterElements(int[] nums) {\n        int n = nums.length;\n        int[] res = new int[n];\n        java.util.Arrays.fill(res, -1);\n        java.util.Deque<Integer> st = new java.util.ArrayDeque<>();\n        for (int i = 2 * n - 1; i >= 0; i--) {\n            while (!st.isEmpty() && st.peek() <= nums[i % n]) st.pop();\n            if (i < n && !st.isEmpty()) res[i] = st.peek();\n            st.push(nums[i % n]);\n        }\n        return res;\n    }\n}",
        csharp: "public class Solution {\n    public int[] NextGreaterElements(int[] nums) {\n        int n = nums.Length;\n        int[] res = new int[n];\n        Array.Fill(res, -1);\n        var st = new Stack<int>();\n        for (int i = 2 * n - 1; i >= 0; i--) {\n            while (st.Count > 0 && st.Peek() <= nums[i % n]) st.Pop();\n            if (i < n && st.Count > 0) res[i] = st.Peek();\n            st.Push(nums[i % n]);\n        }\n        return res;\n    }\n}"
      } }
  ] },
  "a2z-239": { approaches: [
    { id: "mono-inc-stack", title: "Increasing monotone stack", level: "Optimal", time: "O(n)", space: "O(n)",
      explanation: "Traverse right-to-left with an increasing stack; the next smaller is the first element smaller than current on top.",
      code: {
        java: "class Solution {\n    int[] nextSmaller(int[] a) {\n        int n = a.length;\n        int[] res = new int[n];\n        java.util.Deque<Integer> st = new java.util.ArrayDeque<>();\n        for (int i = n - 1; i >= 0; i--) {\n            while (!st.isEmpty() && st.peek() >= a[i]) st.pop();\n            res[i] = st.isEmpty() ? -1 : st.peek();\n            st.push(a[i]);\n        }\n        return res;\n    }\n}",
        csharp: "public class Solution {\n    public int[] NextSmaller(int[] a) {\n        int n = a.Length;\n        int[] res = new int[n];\n        var st = new Stack<int>();\n        for (int i = n - 1; i >= 0; i--) {\n            while (st.Count > 0 && st.Peek() >= a[i]) st.Pop();\n            res[i] = st.Count == 0 ? -1 : st.Peek();\n            st.Push(a[i]);\n        }\n        return res;\n    }\n}"
      } }
  ] },
  "a2z-240": { approaches: [
    { id: "mono-stack-count", title: "Count greater elements to right via stack", level: "Optimal", time: "O(n)", space: "O(n)",
      explanation: "Use a monotone approach: for each element, pop all smaller elements and record the count of remaining stack size.",
      code: {
        java: "class Solution {\n    int[] countGreater(int[] a) {\n        int n = a.length;\n        int[] res = new int[n];\n        java.util.Deque<Integer> st = new java.util.ArrayDeque<>();\n        for (int i = n - 1; i >= 0; i--) {\n            while (!st.isEmpty() && st.peek() <= a[i]) st.pop();\n            res[i] = st.size();\n            st.push(a[i]);\n        }\n        return res;\n    }\n}",
        csharp: "public class Solution {\n    public int[] CountGreater(int[] a) {\n        int n = a.Length;\n        int[] res = new int[n];\n        var st = new Stack<int>();\n        for (int i = n - 1; i >= 0; i--) {\n            while (st.Count > 0 && st.Peek() <= a[i]) st.Pop();\n            res[i] = st.Count;\n            st.Push(a[i]);\n        }\n        return res;\n    }\n}"
      } }
  ] },
  "a2z-241": { approaches: [
    { id: "two-pointer", title: "Left/right max two-pointer", level: "Optimal", time: "O(n)", space: "O(1)",
      explanation: "Track leftMax and rightMax from both ends; water at each bar is min(leftMax, rightMax) - height.",
      code: {
        java: "class Solution {\n    int trap(int[] h) {\n        int l = 0, r = h.length - 1, lm = 0, rm = 0, water = 0;\n        while (l < r) {\n            if (h[l] < h[r]) {\n                if (h[l] >= lm) lm = h[l]; else water += lm - h[l];\n                l++;\n            } else {\n                if (h[r] >= rm) rm = h[r]; else water += rm - h[r];\n                r--;\n            }\n        }\n        return water;\n    }\n}",
        csharp: "public class Solution {\n    public int Trap(int[] h) {\n        int l = 0, r = h.Length - 1, lm = 0, rm = 0, water = 0;\n        while (l < r) {\n            if (h[l] < h[r]) {\n                if (h[l] >= lm) lm = h[l]; else water += lm - h[l];\n                l++;\n            } else {\n                if (h[r] >= rm) rm = h[r]; else water += rm - h[r];\n                r--;\n            }\n        }\n        return water;\n    }\n}"
      } }
  ] },
  "a2z-242": { approaches: [
    { id: "mono-stack-contribution", title: "Count subarrays where each element is min", level: "Optimal", time: "O(n)", space: "O(n)",
      explanation: "For each element, find the distance to previous-less and next-less-or-equal via monotone stack; its contribution is a[i] * left * right.",
      code: {
        java: "class Solution {\n    int sumSubarrayMins(int[] a) {\n        int MOD = 1_000_000_007, n = a.length;\n        long res = 0;\n        java.util.Deque<Integer> st = new java.util.ArrayDeque<>();\n        for (int i = 0; i <= n; i++) {\n            while (!st.isEmpty() && a[st.peek()] > (i == n ? 0 : a[i])) {\n                int mid = st.pop();\n                int left = st.isEmpty() ? -1 : st.peek();\n                res = (res + (long) a[mid] * (mid - left) * (i - mid)) % MOD;\n            }\n            st.push(i);\n        }\n        return (int) res;\n    }\n}",
        csharp: "public class Solution {\n    public int SumSubarrayMins(int[] a) {\n        int MOD = 1_000_000_007, n = a.Length;\n        long res = 0;\n        var st = new Stack<int>();\n        for (int i = 0; i <= n; i++) {\n            while (st.Count > 0 && a[st.Peek()] > (i == n ? 0 : a[i])) {\n                int mid = st.Pop();\n                int left = st.Count == 0 ? -1 : st.Peek();\n                res = (res + (long) a[mid] * (mid - left) * (i - mid)) % MOD;\n            }\n            st.Push(i);\n        }\n        return (int) res;\n    }\n}"
      } }
  ] },
  "a2z-243": { approaches: [
    { id: "stack-sim", title: "Stack simulation of collisions", level: "Optimal", time: "O(n)", space: "O(n)",
      explanation: "Push rightward asteroids; for each leftward one, pop smaller rightward ones until a larger blocks it or it explodes.",
      code: {
        java: "class Solution {\n    int[] asteroidCollision(int[] a) {\n        java.util.Deque<Integer> st = new java.util.ArrayDeque<>();\n        for (int x : a) {\n            boolean alive = true;\n            while (alive && x < 0 && !st.isEmpty() && st.peek() > 0) {\n                if (st.peek() < -x) st.pop();\n                else if (st.peek() == -x) { alive = false; st.pop(); }\n                else alive = false;\n            }\n            if (alive) st.push(x);\n        }\n        int[] res = new int[st.size()];\n        for (int i = res.length - 1; i >= 0; i--) res[i] = st.pop();\n        return res;\n    }\n}",
        csharp: "public class Solution {\n    public int[] AsteroidCollision(int[] a) {\n        var st = new Stack<int>();\n        foreach (int x in a) {\n            bool alive = true;\n            while (alive && x < 0 && st.Count > 0 && st.Peek() > 0) {\n                if (st.Peek() < -x) st.Pop();\n                else if (st.Peek() == -x) { alive = false; st.Pop(); }\n                else alive = false;\n            }\n            if (alive) st.Push(x);\n        }\n        int[] res = st.ToArray();\n        System.Array.Reverse(res);\n        return res;\n    }\n}"
      } }
  ] },
  "a2z-244": { approaches: [
    { id: "mono-min-max", title: "Stack contribution for max and min", level: "Optimal", time: "O(n)", space: "O(n)",
      explanation: "Sum of ranges = sum of subarray maximums minus sum of subarray minimums; compute both via monotone stacks.",
      code: {
        java: "class Solution {\n    long subArrayRanges(int[] a) {\n        return sumMax(a) - sumMin(a);\n    }\n    long sumMax(int[] a) {\n        int n = a.length; long res = 0;\n        java.util.Deque<Integer> st = new java.util.ArrayDeque<>();\n        for (int i = 0; i <= n; i++) {\n            while (!st.isEmpty() && a[st.peek()] <= (i == n ? Integer.MAX_VALUE : a[i])) {\n                int mid = st.pop(); int l = st.isEmpty() ? -1 : st.peek();\n                res += (long) a[mid] * (mid - l) * (i - mid);\n            }\n            st.push(i);\n        }\n        return res;\n    }\n    long sumMin(int[] a) {\n        int n = a.length; long res = 0;\n        java.util.Deque<Integer> st = new java.util.ArrayDeque<>();\n        for (int i = 0; i <= n; i++) {\n            while (!st.isEmpty() && a[st.peek()] >= (i == n ? Integer.MIN_VALUE : a[i])) {\n                int mid = st.pop(); int l = st.isEmpty() ? -1 : st.peek();\n                res += (long) a[mid] * (mid - l) * (i - mid);\n            }\n            st.push(i);\n        }\n        return res;\n    }\n}",
        csharp: "public class Solution {\n    public long SubArrayRanges(int[] a) => SumMax(a) - SumMin(a);\n    long SumMax(int[] a) {\n        int n = a.Length; long res = 0; var st = new Stack<int>();\n        for (int i = 0; i <= n; i++) {\n            while (st.Count > 0 && a[st.Peek()] <= (i == n ? int.MaxValue : a[i])) {\n                int mid = st.Pop(); int l = st.Count == 0 ? -1 : st.Peek();\n                res += (long) a[mid] * (mid - l) * (i - mid);\n            }\n            st.Push(i);\n        }\n        return res;\n    }\n    long SumMin(int[] a) {\n        int n = a.Length; long res = 0; var st = new Stack<int>();\n        for (int i = 0; i <= n; i++) {\n            while (st.Count > 0 && a[st.Peek()] >= (i == n ? int.MinValue : a[i])) {\n                int mid = st.Pop(); int l = st.Count == 0 ? -1 : st.Peek();\n                res += (long) a[mid] * (mid - l) * (i - mid);\n            }\n            st.Push(i);\n        }\n        return res;\n    }\n}"
      } }
  ] },
  "a2z-245": { approaches: [
    { id: "mono-stack-remove", title: "Greedy monotone stack removal", level: "Optimal", time: "O(n)", space: "O(n)",
      explanation: "Build the smallest number by popping larger digits from the stack while k removals remain; trim trailing zeros.",
      code: {
        java: "class Solution {\n    String removeKdigits(String num, int k) {\n        java.util.Deque<Character> st = new java.util.ArrayDeque<>();\n        for (char c : num.toCharArray()) {\n            while (k > 0 && !st.isEmpty() && st.peek() > c) { st.pop(); k--; }\n            st.push(c);\n        }\n        while (k-- > 0 && !st.isEmpty()) st.pop();\n        StringBuilder sb = new StringBuilder();\n        for (char c : st) sb.append(c);\n        String res = sb.toString().replaceFirst(\"^0+\", \"\");\n        return res.isEmpty() ? \"0\" : res;\n    }\n}",
        csharp: "public class Solution {\n    public string RemoveKdigits(string num, int k) {\n        var st = new Stack<char>();\n        foreach (char c in num) {\n            while (k > 0 && st.Count > 0 && st.Peek() > c) { st.Pop(); k--; }\n            st.Push(c);\n        }\n        while (k-- > 0 && st.Count > 0) st.Pop();\n        char[] arr = st.ToArray();\n        System.Array.Reverse(arr);\n        string res = new string(arr).TrimStart('0');\n        return res.Length == 0 ? \"0\" : res;\n    }\n}"
      } }
  ] },
  "a2z-246": { approaches: [
    { id: "mono-stack-rect", title: "Monotone stack for histogram", level: "Optimal", time: "O(n)", space: "O(n)",
      explanation: "Use a sentinel-augmented increasing stack; at each pop the bar forms a rectangle spanning from prev-smaller to current index.",
      code: {
        java: "class Solution {\n    int largestRectangleArea(int[] h) {\n        int n = h.length, best = 0;\n        java.util.Deque<Integer> st = new java.util.ArrayDeque<>();\n        for (int i = 0; i <= n; i++) {\n            while (!st.isEmpty() && h[st.peek()] > (i == n ? 0 : h[i])) {\n                int ht = h[st.pop()];\n                int left = st.isEmpty() ? -1 : st.peek();\n                best = Math.max(best, ht * (i - left - 1));\n            }\n            st.push(i);\n        }\n        return best;\n    }\n}",
        csharp: "public class Solution {\n    public int LargestRectangleArea(int[] h) {\n        int n = h.Length, best = 0;\n        var st = new Stack<int>();\n        for (int i = 0; i <= n; i++) {\n            while (st.Count > 0 && h[st.Peek()] > (i == n ? 0 : h[i])) {\n                int ht = h[st.Pop()];\n                int left = st.Count == 0 ? -1 : st.Peek();\n                best = System.Math.Max(best, ht * (i - left - 1));\n            }\n            st.Push(i);\n        }\n        return best;\n    }\n}"
      } }
  ] },
  "a2z-247": { approaches: [
    { id: "histogram-rows", title: "Largest rectangle per row as histogram", level: "Optimal", time: "O(mn)", space: "O(n)",
      explanation: "Build a histogram row by row (consecutive 1s height) and apply the stack-based largest-rectangle on each row.",
      code: {
        java: "class Solution {\n    int maximalRectangle(char[][] m) {\n        if (m.length == 0) return 0;\n        int rows = m.length, cols = m[0].length, best = 0;\n        int[] h = new int[cols];\n        for (int i = 0; i < rows; i++) {\n            for (int j = 0; j < cols; j++) h[j] = m[i][j] == '1' ? h[j] + 1 : 0;\n            best = Math.max(best, largestHist(h));\n        }\n        return best;\n    }\n    int largestHist(int[] h) {\n        int n = h.length, best = 0;\n        java.util.Deque<Integer> st = new java.util.ArrayDeque<>();\n        for (int i = 0; i <= n; i++) {\n            while (!st.isEmpty() && h[st.peek()] > (i == n ? 0 : h[i])) {\n                int ht = h[st.pop()]; int l = st.isEmpty() ? -1 : st.peek();\n                best = Math.max(best, ht * (i - l - 1));\n            }\n            st.push(i);\n        }\n        return best;\n    }\n}",
        csharp: "public class Solution {\n    public int MaximalRectangle(char[][] m) {\n        if (m.Length == 0) return 0;\n        int rows = m.Length, cols = m[0].Length, best = 0;\n        int[] h = new int[cols];\n        for (int i = 0; i < rows; i++) {\n            for (int j = 0; j < cols; j++) h[j] = m[i][j] == '1' ? h[j] + 1 : 0;\n            best = System.Math.Max(best, LargestHist(h));\n        }\n        return best;\n    }\n    int LargestHist(int[] h) {\n        int n = h.Length, best = 0; var st = new Stack<int>();\n        for (int i = 0; i <= n; i++) {\n            while (st.Count > 0 && h[st.Peek()] > (i == n ? 0 : h[i])) {\n                int ht = h[st.Pop()]; int l = st.Count == 0 ? -1 : st.Peek();\n                best = System.Math.Max(best, ht * (i - l - 1));\n            }\n            st.Push(i);\n        }\n        return best;\n    }\n}"
      } }
  ] },
  "a2z-248": { approaches: [
    { id: "deque-window", title: "Decreasing monotone deque", level: "Optimal", time: "O(n)", space: "O(k)",
      explanation: "Maintain an index deque in decreasing value order; the front always holds the window maximum.",
      code: {
        java: "class Solution {\n    int[] maxSlidingWindow(int[] nums, int k) {\n        int n = nums.length;\n        int[] res = new int[n - k + 1];\n        java.util.Deque<Integer> dq = new java.util.ArrayDeque<>();\n        for (int i = 0; i < n; i++) {\n            while (!dq.isEmpty() && nums[dq.peekLast()] <= nums[i]) dq.pollLast();\n            dq.addLast(i);\n            if (dq.peekFirst() <= i - k) dq.pollFirst();\n            if (i >= k - 1) res[i - k + 1] = nums[dq.peekFirst()];\n        }\n        return res;\n    }\n}",
        csharp: "public class Solution {\n    public int[] MaxSlidingWindow(int[] nums, int k) {\n        int n = nums.Length;\n        int[] res = new int[n - k + 1];\n        var dq = new LinkedList<int>();\n        for (int i = 0; i < n; i++) {\n            while (dq.Count > 0 && nums[dq.Last] <= nums[i]) dq.RemoveLast();\n            dq.AddLast(i);\n            if (dq.First <= i - k) dq.RemoveFirst();\n            if (i >= k - 1) res[i - k + 1] = nums[dq.First];\n        }\n        return res;\n    }\n}"
      } }
  ] },
  "a2z-249": { approaches: [
    { id: "stack-span", title: "Stock span via monotone stack", level: "Optimal", time: "O(n)", space: "O(n)",
      explanation: "Pop smaller-or-equal prices; span = current index minus the index of the first larger price (or i+1 if none).",
      code: {
        java: "class Solution {\n    int[] stockSpan(int[] prices) {\n        int n = prices.length;\n        int[] res = new int[n];\n        java.util.Deque<Integer> st = new java.util.ArrayDeque<>();\n        for (int i = 0; i < n; i++) {\n            while (!st.isEmpty() && prices[st.peek()] <= prices[i]) st.pop();\n            res[i] = st.isEmpty() ? i + 1 : i - st.peek();\n            st.push(i);\n        }\n        return res;\n    }\n}",
        csharp: "public class Solution {\n    public int[] StockSpan(int[] prices) {\n        int n = prices.Length;\n        int[] res = new int[n];\n        var st = new Stack<int>();\n        for (int i = 0; i < n; i++) {\n            while (st.Count > 0 && prices[st.Peek()] <= prices[i]) st.Pop();\n            res[i] = st.Count == 0 ? i + 1 : i - st.Peek();\n            st.Push(i);\n        }\n        return res;\n    }\n}"
      } }
  ] },
  "a2z-250": { approaches: [
    { id: "elimination", title: "Stack-based elimination", level: "Optimal", time: "O(n)", space: "O(n)",
      explanation: "Push all candidates; pop pairs via knows() checks. The remaining candidate is verified in O(n).",
      code: {
        java: "class Solution {\n    int celebrity(int[][] knows) {\n        int n = knows.length;\n        java.util.Deque<Integer> st = new java.util.ArrayDeque<>();\n        for (int i = 0; i < n; i++) st.push(i);\n        while (st.size() > 1) {\n            int a = st.pop(), b = st.pop();\n            if (knows[a][b] == 1) st.push(b); else st.push(a);\n        }\n        int c = st.pop();\n        for (int i = 0; i < n; i++) {\n            if (i != c && (knows[c][i] == 1 || knows[i][c] == 0)) return -1;\n        }\n        return c;\n    }\n}",
        csharp: "public class Solution {\n    public int Celebrity(int[][] knows) {\n        int n = knows.Length;\n        var st = new Stack<int>();\n        for (int i = 0; i < n; i++) st.Push(i);\n        while (st.Count > 1) {\n            int a = st.Pop(), b = st.Pop();\n            if (knows[a][b] == 1) st.Push(b); else st.Push(a);\n        }\n        int c = st.Pop();\n        for (int i = 0; i < n; i++)\n            if (i != c && (knows[c][i] == 1 || knows[i][c] == 0)) return -1;\n        return c;\n    }\n}"
      } }
  ] },
  "a2z-251": { approaches: [
    { id: "hashmap-dll", title: "HashMap + doubly-linked list", level: "Optimal", time: "O(1)", space: "O(capacity)",
      explanation: "Doubly-linked list maintains access order; HashMap gives O(1) lookup. On get/put, move node to front; evict tail when over capacity.",
      code: {
        java: "class Solution {\n    static class LRUCache {\n        int cap;\n        java.util.Map<Integer, Node> map;\n        Node head, tail;\n        static class Node { int k, v; Node prev, next; Node(int k, int v){this.k=k;this.v=v;} }\n        LRUCache(int capacity) {\n            cap = capacity; map = new java.util.HashMap<>();\n            head = new Node(0,0); tail = new Node(0,0);\n            head.next = tail; tail.prev = head;\n        }\n        int get(int key) {\n            if (!map.containsKey(key)) return -1;\n            Node n = map.get(key); remove(n); addFront(n);\n            return n.v;\n        }\n        void put(int key, int value) {\n            if (map.containsKey(key)) { Node old = map.get(key); old.v = value; remove(old); addFront(old); return; }\n            Node n = new Node(key, value);\n            if (map.size() == cap) { Node lru = tail.prev; remove(lru); map.remove(lru.k); }\n            addFront(n); map.put(key, n);\n        }\n        void remove(Node n) { n.prev.next = n.next; n.next.prev = n.prev; }\n        void addFront(Node n) { n.next = head.next; n.prev = head; head.next.prev = n; head.next = n; }\n    }\n}",
        csharp: "public class LRUCache {\n    class Node { public int K, V; public Node Prev, Next; }\n    int cap; Dictionary<int, Node> map = new(); Node head, tail;\n    public LRUCache(int capacity) {\n        cap = capacity; head = new Node(); tail = new Node();\n        head.Next = tail; tail.Prev = head;\n    }\n    public int Get(int key) {\n        if (!map.ContainsKey(key)) return -1;\n        var n = map[key]; Remove(n); AddFront(n); return n.V;\n    }\n    public void Put(int key, int value) {\n        if (map.ContainsKey(key)) { var old = map[key]; old.V = value; Remove(old); AddFront(old); return; }\n        var n = new Node { K = key, V = value };\n        if (map.Count == cap) { var lru = tail.Prev; Remove(lru); map.Remove(lru.K); }\n        AddFront(n); map[key] = n;\n    }\n    void Remove(Node n) { n.Prev.Next = n.Next; n.Next.Prev = n.Prev; }\n    void AddFront(Node n) { n.Next = head.Next; n.Prev = head; head.Next.Prev = n; head.Next = n; }\n}"
      } }
  ] },
  "a2z-252": { approaches: [
    { id: "freq-buckets", title: "Freq map + doubly-linked buckets", level: "Optimal", time: "O(1)", space: "O(capacity)",
      explanation: "Track frequency with bucket doubly-linked lists ordered by time; evict from the lowest-frequency bucket's oldest node.",
      code: {
        java: "class Solution {\n    static class LFUCache {\n        int cap, minFreq;\n        java.util.Map<Integer, Node> keyMap;\n        java.util.Map<Integer, java.util.LinkedHashSet<Integer>> freqMap;\n        static class Node { int k, v, freq; Node(int k, int v){this.k=k;this.v=v;freq=1;} }\n        LFUCache(int capacity) { cap=capacity; minFreq=0; keyMap=new java.util.HashMap<>(); freqMap=new java.util.HashMap<>(); }\n        int get(int key) {\n            if (!keyMap.containsKey(key)) return -1;\n            Node n = keyMap.get(key); touch(n); return n.v;\n        }\n        void put(int key, int value) {\n            if (cap == 0) return;\n            if (keyMap.containsKey(key)) { keyMap.get(key).v = value; touch(keyMap.get(key)); return; }\n            if (keyMap.size() == cap) {\n                var set = freqMap.get(minFreq);\n                int evict = set.iterator().next(); set.remove(evict); keyMap.remove(evict);\n            }\n            Node n = new Node(key, value); keyMap.put(key, n);\n            freqMap.computeIfAbsent(1, x -> new java.util.LinkedHashSet<>()).add(key);\n            minFreq = 1;\n        }\n        void touch(Node n) {\n            int f = n.freq; n.freq++;\n            freqMap.get(f).remove(n.k);\n            if (f == minFreq && freqMap.get(f).isEmpty()) minFreq++;\n            freqMap.computeIfAbsent(n.freq, x -> new java.util.LinkedHashSet<>()).add(n.k);\n        }\n    }\n}",
        csharp: "public class LFUCache {\n    class Node { public int K, V, Freq; public Node(int k, int v) { K=k; V=v; Freq=1; } }\n    int cap, minFreq; Dictionary<int, Node> keyMap = new(); Dictionary<int, LinkedHashSet<int>> freqMap = new();\n    public LFUCache(int capacity) { cap = capacity; }\n    public int Get(int key) { if (!keyMap.ContainsKey(key)) return -1; var n = keyMap[key]; Touch(n); return n.V; }\n    public void Put(int key, int value) {\n        if (cap == 0) return;\n        if (keyMap.ContainsKey(key)) { keyMap[key].V = value; Touch(keyMap[key]); return; }\n        if (keyMap.Count == cap) {\n            var set = freqMap[minFreq]; int evict = set.First(); set.Remove(evict); keyMap.Remove(evict);\n        }\n        var node = new Node(key, value); keyMap[key] = node;\n        if (!freqMap.ContainsKey(1)) freqMap[1] = new LinkedHashSet<int>();\n        freqMap[1].Add(key); minFreq = 1;\n    }\n    void Touch(Node n) {\n        int f = n.Freq; n.Freq++;\n        freqMap[f].Remove(n.K);\n        if (f == minFreq && freqMap[f].Count == 0) minFreq++;\n        if (!freqMap.ContainsKey(n.Freq)) freqMap[n.Freq] = new LinkedHashSet<int>();\n        freqMap[n.Freq].Add(n.K);\n    }\n}"
      } }
  ] }
};
